version: '3.6'

services:
    postgres:
        image: postgres:latest
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_PASSWORD=kidsloop
            - POSTGRES_DB=audio_db
    minio:
        image: minio/minio:latest
        # volumes:
        #     - minio_data:/data
        ports:
             - '9000:9000'
        command: ['server', '/data']
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=minio123
    redis:
        image: 'redis:alpine'
        command: 'redis-server --appendonly yes'
        ports:
            - '6379:6379'
        # volumes:
        #     - redis_data:/data
    # Creates buckets for S3
    minio_init:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc config host add audio-minio http://minio:9000 minio minio123 --api S3v4;
            /usr/bin/mc mb audio-minio/test-org-public-keys;
            /usr/bin/mc mb audio-minio/test-org-private-keys;
            /usr/bin/mc mb audio-minio/test-audio-recordings;
            exit 0;
            "
    audio-service:
        build: ./
        ports:
            - '8080:8080'
        depends_on:
            - postgres
            - minio
            - minio_init
            - redis
        environment:
            - DOMAIN=localhost:8080
            - AWS_ACCESS_KEY_ID=minio
            - AWS_SECRET_ACCESS_KEY=minio123
            - METADATA_DATABASE_URL=postgres://postgres:kidsloop@localhost:5432/audio_db
            - AWS_S3_ENDPOINT=http://minio:9000
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PUBLIC_KEY_BUCKET=test-org-public-keys
            - PRIVATE_KEY_BUCKET=test-org-private-keys
            - AUDIO_FILE_BUCKET=test-audio-recordings
            - LOG_STYLE=SILENT
            - NEW_RELIC_HOME=tests
        # volumes:
        #     - h5p_data:/home/node/h5p-nodejs-library/h5p
    # loadbalancer:
    #     image: nginx:latest
    #     volumes:
    #         - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #     depends_on:
    #         - h5p
    #     ports:
    #         - 8080:8080

# volumes:
#     mongodb_data:
#     minio_data:
#     redis_data:
#     h5p_data: