version: '3.6'

services:
    postgres:
        image: postgres:latest
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_PASSWORD=kidsloop
            - POSTGRES_DB=media_db
    minio:
        image: minio/minio:latest
        # volumes:
        #     - minio_data:/data
        ports:
             - '9000:9000'
             - '9001:9001'
        command: server /data --console-address ":9001"
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=minio123
    redis:
        image: 'redis:alpine'
        command: 'redis-server --appendonly yes'
        ports:
            - '6379:6379'
        # volumes:
        #     - redis_data:/data
    # Creates buckets for S3
    minio_init:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc mb media-minio/test-org-public-keys;
            /usr/bin/mc mb media-minio/test-org-private-keys;
            /usr/bin/mc mb media-minio/test-media-files;
            exit 0;
            "
    # media:
    #     build: ./
    #     ports:
    #         - '8080:8080'
    #     depends_on:
    #         - postgres
    #         - minio
    #         - minio_init
    #         - redis
    #     environment:
    #         - DOMAIN=localhost:8080
    #         - AWS_ACCESS_KEY_ID=minio
    #         - AWS_SECRET_ACCESS_KEY=minio123
    #         - METADATA_DATABASE_URL=postgres://postgres:kidsloop@localhost:5432/media_db
    #         - AWS_S3_ENDPOINT=http://minio:9000
    #         - REDIS_HOST=redis
    #         - REDIS_PORT=6379
    #         - PUBLIC_KEY_BUCKET=test-org-public-keys
    #         - PRIVATE_KEY_BUCKET=test-org-private-keys
    #         - MEDIA_FILE_BUCKET=test-media-files
    #         - LOG_STYLE=SILENT
    #         - NEW_RELIC_HOME=tests
        # volumes:
        #     - media_data:/data

# volumes:
#     mongodb_data:
#     minio_data:
#     redis_data:
#     media_data: