version: '3.6'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=kidsloop
      - POSTGRES_DB=media_db
  minio:
    image: minio/minio:latest
    # volumes:
    #     - minio_data:/data
    ports:
      # Port is set to 80 because of an S3/MinIO bug. Otherwise, the presigned URL fetch tests fail.
      # Details: https://github.com/minio/minio/issues/10361#issuecomment-721345732
      - '80:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
  redis:
    image: 'redis:alpine'
    command: 'redis-server --appendonly yes'
    ports:
      - '6379:6379'
    # volumes:
    #     - redis_data:/data
  # Creates buckets for S3
  minio_init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc mb media-minio/public-keys;
      /usr/bin/mc mb media-minio/private-keys;
      /usr/bin/mc mb media-minio/media-files;
      exit 0;
      "

#   media:
#     build: ./
#     ports:
#       - '8080:8080'
#     depends_on:
#       - postgres
#       - minio
#       - minio_init
#       - redis
#     environment:
#       - DOMAIN=localhost:8080
#       - AWS_ACCESS_KEY_ID=minio
#       - AWS_SECRET_ACCESS_KEY=minio123
#       - METADATA_DATABASE_URL=postgres://postgres:kidsloop@localhost:5432/media_db
#       - AWS_S3_ENDPOINT=http://minio:9000
#       - REDIS_HOST=redis
#       - REDIS_PORT=6379
#       - PUBLIC_KEY_BUCKET=public-keys
#       - PRIVATE_KEY_BUCKET=private-keys
#       - MEDIA_FILE_BUCKET=media-files
#       - LOG_STYLE=SILENT
#       - NEW_RELIC_HOME=localDev
#     volumes:
#       - media_data:/data

# volumes:
#   mongodb_data:
#   minio_data:
#   redis_data:
#   media_data:
