name: Release

on:
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # npm-ci:
  #   uses: KL-Engineering/github-action-workflows/.github/workflows/npm-ci.yml@v2.1.0
  #   secrets:
  #     NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

  # npm-test:
  #   needs: [npm-ci]
  #   uses: ./.github/workflows/job-test.yml
  
  create-release:
    # needs: [npm-test]
    uses: ./.github/workflows/job-create-release.yml
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
  
  deploy-alpha:
    needs: [create-release]
    uses: ./.github/workflows/job-deploy-alpha.yml
    with:
      ecs_aws_service: kl-alpha-h5p-audio
    secrets:
      AWS_ACCESS_KEY_ID_ALPHA_DEV: ${{ secrets.AWS_ACCESS_KEY_ID_ALPHA_DEV }}
      AWS_SECRET_ACCESS_KEY_ALPHA_DEV: ${{ secrets.AWS_SECRET_ACCESS_KEY_ALPHA_DEV }}